import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Demo from "./Demo";
import Providers from "@/components/Providers";
import Header from "@/components/Header";
import StoreProvider from "@/components/StoreProvider";

const josefinSans = Josefin_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Dev Event",
  description: "Generated by Nott Nott",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={josefinSans.className}
        >
          <Providers>
            {/* <Demo /> */}
            <Header />
            <main>
              {children}
            </main>
          </Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
